### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by fangmarks** [richhenderson/nanotsdb#1]
Could you by any chance allow the option to have the Database Autosave after every change or every X seconds?

**Comment by richhenderson** [comment]
Easily. Do you think all actions should be a promise that returns when saved?

**Comment by fangmarks** [comment]
That'd make sense if someone plans to re-use parts of it later down the line, imo

**Comment by richhenderson** [comment]
Is this something you would like me to do or would you like to submit pull request for?

**Comment by fangmarks** [comment]
I'd appreciate if you did it, I'm rather unfamiliar with this code

**Comment by richhenderson** [comment]
Ok no problem. The code is really simple ts file.

Perhaps if you could explain how you expect it to work,  it would help me to make it better for you?

It only has a few API calls. Perhaps you could help me improve it by telling me what you expect to call and what you expect to happen when you call it?

**Comment by fangmarks** [comment]
I'd expect it to save after any action (i.e. insert, delete, etc.), though I'm not sure how good that'd be considering JSON dbs are apparently prone to corrupting

**Comment by richhenderson** [comment]
I think the reason not to save after any transaction is that saving to disk is slow and adding or removing is fast... if everything saves to disk on every transaction, perhaps a whole new API is required?

This is entirely possible and I'm happy to make it like that. I will make time to change it in the next 48 hours.

**Comment by richhenderson** [comment]
This feature has been added to v1.1.0 and the issue is now closed
